<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <span>Mini eCommerce Site</span>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'chargers'),
            'default',
            true) ?>">Chargers</a>
        <a href="<?php echo $this->url(
            array('controller'=>'cases'),
            'default',
            true) ?>">Cases</a>
    </div>
    <div id="notice" style="clear:both"><br />
        <span>After "vagrant up" run the following commands to load the database</span><br />
        <span>vagrant ssh</span><br />
        <span>mysqladmin -u root -psqlpass create mycms</span><br />
        <span>mysql -u root -psqlpass mycms &lt; /var/www/build/sql/schema.sql</span><br /><br /><br />
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>